databases:
  - name: sellsmart
    databaseName: sellsmart
    user:  

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sellsmart
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    type: redis
    name: redis
    ipAllowlist: []
    plan: free
    maxmemoryPolicy: noeviction    